resume: /cpfs01/user/zhanghanxue/segment-anything/exps/all_point_box_depth/0227-002210/checkpoint_88.pth

output_rotation_matrix: True
contain_edge_obj: False
unlock_all_backbone: false

tune_with_prompt: True
inference_with_prompt: True

max_depth: 100

dino_dim: 1024
dino_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/dinov2_vitl14_pretrain.pth"

model:
  type: 'vit_h'
  checkpoint: '/cpfs01/user/zhanghanxue/segment-anything/sam_vit_h_4b8939.pth'
  pad: 896
  image_encoder:
    img_size: 1024
    patch_size: 16
    in_chans: 3
    embed_dim: 1280
    depth: 32
    num_heads: 16
    mlp_ratio: 4.0
    out_chans: 256
    qkv_bias: True
    norm_layer: nn.LayerNorm
    act_layer: nn.GELU
    use_abs_pos: True
    use_rel_pos: True
    rel_pos_zero_init: True
    window_size: 14
    global_attn_indexes: [7, 15, 23, 31]
  prompt_encoder:
  mask_decoder:
    num_multimask_outputs: 3
    type: MaskDecoder
  freeze:
    image_encoder: False
    prompt_encoder: False
    mask_decoder: False
  
  additional_adapter: True
  vit_pad_mask: True
  original_sam: False
  multi_level_box_output: 3

dataset:
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  