batch_size: 1
num_epochs: 90
eval_interval: 1
inference_only: True
exp_dir: "./exps/inference"
resume: ./checkpoints/detany3d_ckpts/zero_shot_category_ckpt.pth
resume_scheduler: False
use_amp: False
max_depth: 100

add_cubercnn_for_ap_inference: True
output_json_file: output_results

tune_with_prompt: True
inference_with_prompt: True
tune_with_depth: True
inference_with_depth: True
provide_gt_intrinsics: True
provide_gt_intrinsics_inference: True

# prompt
input_point_prompt: False
inference_with_point_prompt: False
input_box_prompt: True
inference_with_box_prompt: True
random_drop_prompt: True
random_drop_prompt_prob: 0.7
random_drop_depth_prompt_prob: 0.7

inference_novel: True
inference_basic: False

output_rotation_matrix: True
contain_edge_obj: False

visualize_num: 10

# loss
loss:
  loss_list: ['depth_loss', 'intrinsic_loss', '2d_bbox_loss', '3d_bbox_loss', 'chamfer_loss']
  depth:
    coefficient: 0.15
    depth_loss_weight: 10
  phi:
    coefficient: 1
    phi_loss_weight: 2.5
  theta:
    coefficient: 1
    theta_loss_weight: 2.5

unlock_all_backbone: false

# unidepth related parameters
load_unidepth_ckpt: True
dino_dim: 1024
unidepth_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/model.pth'
dino_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/dinov2_vitl14_pretrain.pth"

# optmizer
opt: 
  type: v3
  learning_rate: 0.00001
  min_learning_rate: 0.000000001
  weight_decay: 0.0000001
  warmup_steps: 1000
  unidepth_lr: 0.0000001
  unidepth_weight_decay: 0.000000001

model:
  type: 'vit_h'
  checkpoint: './checkpoints/sam_ckpts/sam_vit_h_4b8939.pth'
  pad: 896
  image_encoder:
    img_size: 1024
    patch_size: 16
    in_chans: 3
    embed_dim: 1280
    depth: 32
    num_heads: 16
    mlp_ratio: 4.0
    out_chans: 256
    qkv_bias: True
    norm_layer: nn.LayerNorm
    act_layer: nn.GELU
    use_abs_pos: True
    use_rel_pos: True
    rel_pos_zero_init: True
    window_size: 14
    global_attn_indexes: [7, 15, 23, 31]
  prompt_encoder:
  mask_decoder:
    num_multimask_outputs: 3
    type: MaskDecoder
  freeze:
    image_encoder: False
    prompt_encoder: False
    mask_decoder: False
  
  additional_adapter: True
  vit_pad_mask: True
  original_sam: False
  multi_level_box_output: 3

dataset:
  generate_dino_oracle_list: False
  dino_as_input: True
  previous_metric: True
  dino_oracle_input: False
  zero_shot: True
  zero_shot_dataset: False
  clamp_bbox_2d: True
  perturbation_point_prompt: False
  perturbation_box_prompt: True
  perturbation_factor: 0.3
  num_point_prompts: 1
  generate_point_prompts_via_mask: True
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  max_dets: 50
  hack_img_path: False
  hack_point_prompt: False
  hack_box_prompt: False
  train:
    kitti:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 1.
      pkl_path: './data/pkls/omni3d23daw/KITTI_train.pkl'

  val:
    kitti:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 1.
      pkl_path: ./data/pkls/ovmono3d_novel_gt/KITTI_test_novel.pkl


    sunrgbd:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 10000.
      pkl_path: ./data/pkls/ovmono3d_novel_gt/SUNRGBD_test_novel.pkl


    arkitscenes:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 1
      pkl_path: ./data/pkls/ovmono3d_novel_gt/ARKitScenes_test_novel.pkl

    
