batch_size: 1
num_epochs: 82
eval_interval: 1
# save_ckpt_interval: 10
inference_only: True
exp_dir: "/cpfs01/user/zhanghanxue/segment-anything/exps/inference"
pretrain_depth: False
# pretrain_depth: '/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/detectany3D_huge/1025/1024-131923/checkpoint_3.pth'
resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/chamfer_unlock_decoder_tt_with_cam_to_det/1109-134707/checkpoint_79.pth'
# resume: False
resume_scheduler: False

tune_with_prompt: True
inference_with_prompt: True
tune_with_depth: True
inference_with_depth: True

provide_gt_intrinsics: True
provide_gt_intrinsics_inference: True

detach_stage_2: False
stage_one_to_stage_three: True

add_dino_feature_to_sam_decoder: False
multi_level_dino: False

# prompt
input_point_prompt: True
inference_with_point_prompt: True
perturbation_prompt: False
perturbation_factor: 0.2
num_pertuerbated_points: 10

input_box_prompt: False
inference_with_box_prompt: False

random_drop_prompt: True


loss:
  loss_list: ['depth_loss', 'intrinsic_loss', '2d_bbox_loss', '3d_bbox_loss', 'chamfer_loss']
  depth:
    coefficient: 0.15
    depth_loss_weight: 10
  phi:
    coefficient: 1
    phi_loss_weight: 2.5
  theta:
    coefficient: 1
    theta_loss_weight: 2.5

unlock_all_backbone: False
zero_conv: True
zero_conv_encoder: False
teacher_model: False

# unidepth related parameters
merge_dino_feature: True
load_unidepth_ckpt: True
add_adapter_with_dino: True
dino_dim: 1024
unidepth_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/model.pth'
dino_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/dinov2_vitl14_pretrain.pth"

# inference_baselines: 'cube_rcnn'
# baseline_result_path: '/cpfs01/user/zhanghanxue/segment-anything/imgpath2results_cubercnn_kitti.json'

opt: 
  type: v1
  learning_rate: 0.0001
  min_learning_rate: 0.00000001
  weight_decay: 0.00001
  warmup_steps: 1000
  unidepth_lr: 0.000001
  unidepth_weight_decay: 0.0000001

  # learning_rate: 0.0000001
  # min_learning_rate: 0.00000000001
  # weight_decay: 0.0000001
  # warmup_steps: 1000
  # unidepth_lr: 0
  # unidepth_weight_decay: 0

  
model:
  type: 'vit_h'
  checkpoint: '/cpfs01/user/zhanghanxue/segment-anything/sam_vit_h_4b8939.pth'
  pad: 896
  image_encoder:
    img_size: 1024
    patch_size: 16
    in_chans: 3
    embed_dim: 1280
    depth: 32
    num_heads: 16
    mlp_ratio: 4.0
    out_chans: 256
    qkv_bias: True
    norm_layer: nn.LayerNorm
    act_layer: nn.GELU
    use_abs_pos: True
    use_rel_pos: True
    rel_pos_zero_init: True
    window_size: 14
    global_attn_indexes: [7, 15, 23, 31]
  prompt_encoder:
  mask_decoder:
    num_multimask_outputs: 3
    type: MaskDecoder
  freeze:
    image_encoder: False
    prompt_encoder: False
    mask_decoder: False
  dpt: False
  unidepth_head: True
  use_adapter: True
  additional_adapter: True
  add_cls_token: True
  vit_pad_mask: True


dataset:
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  train:
    # cityscapes:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/cityscapes3d/cityscapes_train_with_3d_bbox_image_level.pkl'
    kitti:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 1
      metric_scale: 1.
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_train_detany3d_no_occlusion_v3.pkl'
      # pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_train_detany3d_car.pkl'
    # cityscapes_val:
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: "/cpfs01/shared/opendrivelab/cityscapes3d/cityscapes_for_dpt_val.pkl"
    # waymo:
    #   pkl_path: '/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/waymo/waymo_data_train_front.pkl'
  val:
    # cityscapes:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: "/cpfs01/user/zhanghanxue/segment-anything/data/cityscapes3d/cityscapes_val_with_3d_bbox_image_level.pkl"
    # kitti_train:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   # pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_train_detany3d_no_occlusion_v3.pkl'
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_train_detany3d_car.pkl'
    kitti_val:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 1
      metric_scale: 1.
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_val_detany3d_no_occlusion_v3.pkl'
      # pkl_path: "/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_val_detany3d_car.pkl"
    # kitti_train:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   pkl_path: '/cpfs01/shared/opendrivelab/anydet3d/data/kitti/kitti_data_train_detany3d_no_occlusion.pkl'
    
   