batch_size: 1
num_epochs: 50
eval_interval: 5
inference_only: False
teacher_model: True
exp_dir: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/detectany3D_nouse"
# resume: '/cpfs01/shared/opendrivelab/haoran/detectany3D_exp/checkpoint_27.pth'
resume: False
tune_with_prompt: False
tune_with_depth: True
provide_gt_intrinsics: False
vit_pad_mask: True
loss_list: ['depth_loss']
unlock_all_backbone: False
phi_loss_weight: 1
dist_loss_weight: 1
distill_loss_fn: 'mse'

opt: 
  learning_rate: 0.0001
  weight_decay: 0
  decay_factor: 10
  steps: [1000, 60000, 86666]
  warmup_steps: 20
  
model:
  type: 'vit_h'
  checkpoint: 'sam.pth'
  pad: 1024
  image_encoder:
    img_size: 1024
    patch_size: 16
    in_chans: 3
    embed_dim: 1280
    depth: 32
    num_heads: 16
    mlp_ratio: 4.0
    out_chans: 256
    qkv_bias: True
    norm_layer: nn.LayerNorm
    act_layer: nn.GELU
    use_abs_pos: True
    use_rel_pos: True
    rel_pos_zero_init: True
    window_size: 14
    global_attn_indexes: [7, 15, 23, 31]
  prompt_encoder:
  mask_decoder:
  freeze:
    image_encoder: False
    prompt_encoder: True
    mask_decoder: True
  dpt: False
  unidepth_head: True
  use_adapter: True
  add_cls_token: True

dataset:
  train:
    # cityscapes:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 10
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: "/cpfs01/shared/opendrivelab/cityscapes3d/cityscapes_for_dpt_train.pkl"

    # cityscapes_val:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 10
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: "/cpfs01/shared/opendrivelab/cityscapes3d/cityscapes_for_dpt_val.pkl"

    # waymo:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 100
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/"
    #   pkl_path: '/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/waymo/waymo_data_train_front.pkl'

    # drivingstereo_train:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 100
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 255.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/drivingstereo_new/OpenDataLab___DrivingStereo/drivingstereo_train.pkl"

    # drivingstereo_test:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 100
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 255.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/drivingstereo_new/OpenDataLab___DrivingStereo/drivingstereo_test.pkl"

    # taskonomy:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 500
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 512.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/taskonomy/taskonomy_right_0904_522762.pkl"

    # scannetv1:
    #   range:
    #     begin: 0
    #     end: 3000
    #     interval: 1000
    #   max_distance: 5
    #   min_distance: 0.01
    #   metric_scale: 1000.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/ScanNet_formal_unzip/scannet_dataset_filtered.pkl"

    # A2D2:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 10
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/A2D2/OpenDataLab___A2D2/a2d2_front_train0.pkl"

    nuscenes:
      range:
        begin: 0
        end: -1
        interval: 100
      max_distance: 250
      min_distance: 0.01
      metric_scale: 218.45
      pkl_path: "/cpfs01/user/jianghaoran/detany3d/nuscene_pre/nuscenes_train.pkl"
    
    
  val:
    nuscenes:
      range:
        begin: 0
        end: -1
        interval: 2000
      max_distance: 250
      min_distance: 0.01
      metric_scale: 218.45
      pkl_path: "/cpfs01/user/jianghaoran/detany3d/nuscene_pre/nuscenes_train.pkl"
    # cityscapes:
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/val"
    #   pkl_path: "/cpfs01/shared/opendrivelab/cityscapes3d/cityscapes_for_dpt_val.pkl"
    # sunrgbd:
    #   range:
    #     begin: 0
    #     end: 30
    #     interval: 10
    #   max_distance: 5
    #   min_distance: 0.01
    #   metric_scale: 10000.
    #   dataDir: "/cpfs01/user/zhanghanxue/segment-anything/data/sunrgbd/OFFICIAL_SUNRGBD/sun-grbd"
    #   pkl_path: "/cpfs01/shared/opendrivelab/sun-rgbd/sunrgbd_for_dpt_test.pkl"

    # sunrgbd_train:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 10
    #   max_distance: 5
    #   min_distance: 0.01
    #   metric_scale: 10000.
    #   dataDir: "/cpfs01/user/zhanghanxue/segment-anything/data/sunrgbd/OFFICIAL_SUNRGBD/sun-grbd"
    #   pkl_path: "/cpfs01/shared/opendrivelab/sun-rgbd/sunrgbd_for_dpt_train.pkl"

    # drivingstereo_test:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 10
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 255.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/drivingstereo_new/OpenDataLab___DrivingStereo/drivingstereo_test.pkl"