batch_size: 1
num_epochs: 1
eval_interval: 1
# save_ckpt_interval: 10
inference_only: True
exp_dir: "/cpfs01/user/zhanghanxue/segment-anything/exps/masks"
pretrain_depth: False
# resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/sun_kitti_01_nus_mask_point_prompt_random_add_box_rotation_matrix/1206-031314/checkpoint_49.pth'
# pretrain_depth: '/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/detectany3D_huge/1025/1024-131923/checkpoint_3.pth'
# resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/omni3d_mini/1126-161117/checkpoint_79.pth'
# resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/sun_kitti_01_nus_mask_point_prompt_random_add_box_rotation_matrix/1208-173218/checkpoint_39.pth'
# resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/nuscenes_and_kitti_full/1118-192003/checkpoint_49.pth'
# resume: '/cpfs01/user/zhanghanxue/segment-anything/exps/sun_kitti_01_nus_mask_point_prompt_random_add_box_rotation_matrix/1211-130311/checkpoint_79.pth'
# resume: /cpfs01/user/zhanghanxue/segment-anything/exps/load_box_only_9_dof_all_dataset_scaling_up/0207-102742/checkpoint_87.pth
resume: False
resume_scheduler: True
use_ema: False
use_amp: False
max_depth: 100

add_cubercnn_for_ap_inference: False
output_json_file: tab1_9dof
tune_detector_2d: False

tune_with_prompt: True
inference_with_prompt: True
tune_with_depth: True
inference_with_depth: True

provide_gt_intrinsics: True
provide_gt_intrinsics_inference: True

detach_stage_2: False
stage_one_to_stage_three: True

add_dino_feature_to_sam_decoder: False
multi_level_dino: False

# prompt
input_point_prompt: False
inference_with_point_prompt: False
input_box_prompt: True
inference_with_box_prompt: True

inference_novel: True
inference_basic: False

random_drop_prompt: True
random_drop_prompt_prob: 0.7

output_rotation_matrix: True
depth_token_condition: False
contain_edge_obj: False
chamfer_loss_supervise_all: False

# loss
loss:
  loss_list: ['depth_loss', 'intrinsic_loss', '2d_bbox_loss', '3d_bbox_loss', 'corners_loss']
  depth:
    coefficient: 0.15
    depth_loss_weight: 10
  phi:
    coefficient: 1
    phi_loss_weight: 2.5
  theta:
    coefficient: 1
    theta_loss_weight: 2.5

unlock_all_backbone: False
zero_conv: True
zero_conv_encoder: False
teacher_model: False

visualize_num: 1

# unidepth related parameters
merge_dino_feature: True
load_unidepth_ckpt: True
add_adapter_with_dino: True
dino_dim: 1024
unidepth_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/model.pth'
dino_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/dinov2_vitl14_pretrain.pth"

# optmizer
opt: 
  type: v3
  learning_rate: 0.0001
  min_learning_rate: 0.00000001
  weight_decay: 0.0000001
  warmup_steps: 1000
  unidepth_lr: 0.000001
  unidepth_weight_decay: 0.00000001

  # learning_rate: 0.0000001
  # min_learning_rate: 0.00000000001
  # weight_decay: 0.0000001
  # warmup_steps: 1000
  # unidepth_lr: 0
  # unidepth_weight_decay: 0

  
model:
  type: 'vit_h'
  checkpoint: '/cpfs01/user/zhanghanxue/segment-anything/sam_vit_h_4b8939.pth'
  pad: 896
  image_encoder:
    img_size: 1024
    patch_size: 16
    in_chans: 3
    embed_dim: 1280
    depth: 32
    num_heads: 16
    mlp_ratio: 4.0
    out_chans: 256
    qkv_bias: True
    norm_layer: nn.LayerNorm
    act_layer: nn.GELU
    use_abs_pos: True
    use_rel_pos: True
    rel_pos_zero_init: True
    window_size: 14
    global_attn_indexes: [7, 15, 23, 31]
  prompt_encoder:
  mask_decoder:
    num_multimask_outputs: 3
    type: MaskDecoder
  freeze:
    image_encoder: False
    prompt_encoder: False
    mask_decoder: False
  dpt: False
  unidepth_head: True
  use_adapter: True
  additional_adapter: True
  add_cls_token: True
  vit_pad_mask: True
  detector_2d_head: False
  original_sam: True
  multi_level_box_output: 1
  enable_dense_prompt: False


dataset:
  zero_shot: False
  clamp_bbox_2d: True
  perturbation_point_prompt: False
  perturbation_box_prompt: True
  perturbation_factor: 0.1
  num_point_prompts: 1
  generate_point_prompts_via_mask: False
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  max_dets: 50
  hack_img_path: False
  hack_point_prompt: False
  hack_box_prompt: False
  train:
    # cityscapes:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/cityscapes3d/cityscapes_train_with_3d_bbox_image_level.pkl'

    hypersim:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 35
      min_distance: 0.01
      metric_scale: 1.
      pkl_path: /cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/Hypersim_train.pkl

    nuscenes:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 218.45
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/nuscenes/nuscenes_data_train_detany3d_according_to_omni3d.pkl'
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/nuscenes/nuscenes_data_train_detany3d_according_to_omni3d_with_edge_obj.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/nuScenes_train.pkl'

    kitti:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 1.
      pkl_path: './data/pkls/omni3d23daw/KITTI_train.pkl'

    sunrgbd:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 10000.
      # pkl_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/sunrgbd/sunrgbd_data_train_detany3d.pkl"
      pkl_path: "/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/SUNRGBD_train.pkl"
    
    objectron:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 10
      min_distance: 0.01
      metric_scale: 1
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/objectron/objectron_data_train_detany3d_only_bbox.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/Objectron_train.pkl'

    arkitscenes:
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 10
      min_distance: 0.01
      metric_scale: 1
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/arkitscenes/arkitscenes_data_train_detany3d.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/ARKitScenes_train.pkl'

    # coco:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 500
    #   max_distance: 100
    #   min_distance: 0.01
    #   metric_scale: 1
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/coco_train.pkl'
    #   dataDir: './data/coco'
    #   dataType: 'train2017'

    # taskonomy:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 20
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 512.
    #   pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/taskonomy/taskonomy_right_0904_522762.pkl"
    
    # drivingstereo_train:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 2
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 255.
    #  pkl_path: "/cpfs01/shared/opendrivelab/opendrivelab_hdd/haoran/drivingstereo_new/OpenDataLab___DrivingStereo/drivingstereo_train.pkl"

    # A2D2:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 0.01
    #   metric_scale: 218.45
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/other_with_bbox_3d/A2D2_with_box.pkl'

  val:
    # A2D2:
    #   range:
    #     begin: 2
    #     end: -1
    #     interval: 5
    #   max_distance: 100
    #   min_distance: 0.01
    #   metric_scale: 218.45
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/other_with_bbox_3d/A2D2_with_box.pkl'
    # cityscapes:
    #   xywl_mode: True
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/test"
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/cityscapes3d/cityscapes_val_with_3d_bbox_image_level.pkl'
    # waymo:
    #   range:
    #     begin: 0 
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 1
    #   metric_scale: 1.
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/waymo/waymo_data_val_detany3d_stage2.pkl'
    # coco:
    #   range:
    #     begin: 0
    #     end: -1
    #     interval: 1
    #   max_distance: 100
    #   min_distance: 0.01
    #   metric_scale: 1
    #   pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/coco_val.pkl'
    #   dataDir: './data/coco'
    #   dataType: 'val2017'
    kitti:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 1.
      # pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/kitti/kitti_data_val_detany3d_no_occlusion_v3.pkl'
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/kitti/kitti_data_test_detany3d_according_to_omni3d_output.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/KITTI_train.pkl'
      
    nuscenes:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 100
      min_distance: 0.1
      metric_scale: 218.45
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/nuscenes/nuscenes_data_test_detany3d_according_to_omni3d.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/nuScenes_train.pkl'
      # pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/cubercnn2dpred/nuScenes_test.pkl'


    # # # cityscapes:
    # # #   range:
    # # #     begin: 0
    # # #     end: -1
    # # #     interval: 1
    # # #   max_distance: 100
    # # #   min_distance: 1
    # # #   metric_scale: 1.
    # # #   dataDir: "/cpfs01/shared/opendrivelab/cityscapes3d/leftImg8bit/train"
    # # #   pkl_path: "/cpfs01/user/zhanghanxue/segment-anything/data/cityscapes3d/cityscapes_val_with_3d_bbox_image_level.pkl"


    sunrgbd:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 10000.
      # pkl_path: "/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/sunrgbd/sunrgbd_data_test_detany3d.pkl"
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/sunrgbd/sunrgbd_data_test_detany3d_omni3d_output.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/SUNRGBD_train.pkl'

    objectron:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 1
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/objectron/objectron_data_test_detany3d_only_bbox.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/Objectron_train.pkl'

    hypersim:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 35
      min_distance: 0.01
      metric_scale: 1.
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/hypersim/hypersim_data_test_detany3d.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/Hypersim_train.pkl'

    arkitscenes:
      # xywl_mode: True
      range:
        begin: 0
        end: -1
        interval: 1
      max_distance: 5
      min_distance: 0.01
      metric_scale: 1
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/arkitscenes/arkitscenes_data_test_detany3d.pkl'
      # pkl_path: /cpfs01/user/zhanghanxue/segment-anything/data/pkls/cubercnn2dpred/ARKitScenes_test.pkl
      # pkl_path: '/cpfs01/shared/opendrivelab/zhanghanxue/DetAny3D/data/arkitscenes/arkitscenes_data_test_detany3d_with_edge_obj.pkl'
      pkl_path: '/cpfs01/user/zhanghanxue/segment-anything/data/pkls/omni3d23daw/ARKitScenes_train.pkl'